version: 2
jobs:
  test:
    working_directory: /go/src/github.com/broderickhyman/albiondata-client
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports
      - run: make validate-fmt
  build_windows:
    working_directory: /go/src/github.com/broderickhyman/albiondata-client
    docker:
      - image: broderickhyman/mingw-golang
    steps:
      - checkout
      - run: make build-windows
      - store_artifacts:
          path: /go/src/github.com/broderickhyman/albiondata-client/update-windows-amd64.exe.gz
          destination: update-windows-amd64.exe.gz
      - store_artifacts:
          path: /go/src/github.com/broderickhyman/albiondata-client/albiondata-client-amd64-installer.exe
          destination: albiondata-client-amd64-installer.exe
      - persist_to_workspace:
          root: /go/src/github.com/broderickhyman/albiondata-client
          paths:
            - update-windows-amd64.exe.gz
            - albiondata-client-amd64-installer.exe
  build_linux:
    working_directory: /go/src/github.com/broderickhyman/albiondata-client
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: make build-linux
      - store_artifacts:
          path: /go/src/github.com/broderickhyman/albiondata-client/update-linux-amd64.gz
          destination: update-linux-amd64.gz
      - persist_to_workspace:
          root: /go/src/github.com/broderickhyman/albiondata-client
          paths:
            - update-linux-amd64.gz
  build_darwin:
    working_directory: /go/src/github.com/broderickhyman/albiondata-client
    docker:
      - image: broderickhyman/crossbuild-golang
    steps:
      - checkout
      - run: make build-darwin
      - store_artifacts:
          path: /go/src/github.com/broderickhyman/albiondata-client/update-darwin-amd64.gz
          destination: update-darwin-amd64.gz
      - store_artifacts:
          path: /go/src/github.com/broderickhyman/albiondata-client/albiondata-client-amd64-mac.zip
          destination: albiondata-client-amd64-mac.zip
      - persist_to_workspace:
          root: /go/src/github.com/broderickhyman/albiondata-client
          paths:
            - update-darwin-amd64.gz
            - albiondata-client-amd64-mac.zip
  deploy:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/golang:1.17
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u broderickhyman -r albiondata-client $CIRCLE_TAG /tmp/workspace
workflows:
  version: 2
  test_build_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_windows:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - build_linux:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - build_darwin:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build_windows
            - build_linux
            - build_darwin
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
